Tutorial = {}
Tutorial.state = 1

TUTORIAL_KEYS = 1
TUTORIAL_MOVE_FORWARD = 2
TUTORIAL_MOVE_BACKWARD = 3
TUTORIAL_MOVE_FORWARD_WITH_CANVAS = 4
TUTORIAL_MOVE_FORWARD_WITH_CANVAS_SECOND = 5
TUTORIAL_MOVE_BACKWARD_WITH_CANVAS = 6
TUTORIAL_SHOW_BOAT = 10

function Tutorial:init()
end

function Tutorial:update()
end
